### PR TITLE
expand on intro

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2)

### CODE REVIEW

**Review by GrayHatter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2)* status: 0 of 1 files reviewed, 4 unresolved discussions

___
*[DHTAnnouncements.md, line 77 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyfw0l9Ekz7JByRBU1:-LRyfw0l9Ekz7JByRBU2:btlj6uy) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L77)):*
> ```Markdown
> These packets form an RPC DHT Packet pair.
> 
> #### Data Search Request
> ```

We can merge this, and the following packets to save a round trip.

When we announce, if the DHT node has stored data, it'll send it back, and accept/store this data. Then when our friend reconnects to this node to maintain it's announcement, it'll receive our stored data back.

If the node can't, or won't accept the announce we send. It should respond with a list of nodes it thinks might accept our announcement.

This system is trivially less robust, but saves on data use.
___
*[DHTAnnouncements.md, line 94 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyfWfJDZruxbjDIvoC:-LRyfWfK6oC8OZa14-xZ:b-v4otei) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L94)):*
> ```Markdown
> | `[39, 204]` | Node Infos | Nodes in Packed Node Format                 |
> 
> The "announcement would be accepted" boolean should be set to true iff a Store 
> ```

iff meaning and only if? can we expand it?
___
*[DHTAnnouncements.md, line 116 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyhCay1Jpn0ftr_zsL:-LRyhCay1Jpn0ftr_zsM:b-uogq10) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L116)):*
> ```Markdown
> DHT Packet, 8 for UDP header, 20 for IPv4 header), the minimum size of a 
> request is 140 bytes, and the maximum size of a response is 411 bytes, giving 
> an amplification ratio of 2.9. Hopefully not high enough to be useful.
> ```

I'm not convinced this is a concern. The attacker would need to recompute the dest DHT node's request packet every [interval]. And then, if it's attempting to store the same data, with the same nonce, if we want to be verbose we can retransmit the `announce_accepted` packet. Or detect the abuse, and just "ban" that key or src address for [time]. Or am I missing something?

my assumption is that you'd announce to >=3 DHT nodes, to avoid a single node going down, and taking your friend with them.

if we want to be really fancy, we could send a retransmission key that 'victim' address would need to use to get further responses from us.
___
*[DHTAnnouncements.md, line 158 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyiXlVAURKFItIzSo4:-LRyiXlVAURKFItIzSo5:bhiho37) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L158)):*
> ```Markdown
> For a reannouncement, the announcement data is the SHA256 hash of an 
> announcement sent in a previous initial announcement. This is used to extend 
> the lifetime of an announcement without wastefully resending the whole 
> ```

what's the difference in packet sizes?

**Review by GrayHatter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2)* status: 0 of 1 files reviewed, 4 unresolved discussions

___
*[DHTAnnouncements.md, line 116 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyhCay1Jpn0ftr_zsL:-LRyk21YBIl1OGyPnerL:bgowfa) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L116)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

I'm not convinced this is a concern. The attacker would need to recompute the dest DHT node's request packet every [interval]. And then, if it's attempting to store the same data, with the same nonce, if we want to be verbose we can retransmit the `announce_accepted` packet. Or detect the abuse, and just "ban" that key or src address for [time]. Or am I missing something?

my assumption is that you'd announce to >=3 DHT nodes, to avoid a single node going down, and taking your friend with them.

if we want to be really fancy, we could send a retransmission key that 'victim' address would need to use to get further responses from us.
</blockquote></details>

or, there was some discussion about storing messages for offline delivery in the DHT. In one of those discussions, an idea that came up was proof of work. If we add a proof of work system. If we detect possible abuse, we could simply respond to abusive nodes with a POW request every [interval] dropping packets from said node that don't include that POW

**Review by zugz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @GrayHatter)

___
*[DHTAnnouncements.md, line 77 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyfw0l9Ekz7JByRBU1:-LS5oBEY9iAu2vSqOCAv:b-f1aqb1) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L77)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

We can merge this, and the following packets to save a round trip.

When we announce, if the DHT node has stored data, it'll send it back, and accept/store this data. Then when our friend reconnects to this node to maintain it's announcement, it'll receive our stored data back.

If the node can't, or won't accept the announce we send. It should respond with a list of nodes it thinks might accept our announcement.

This system is trivially less robust, but saves on data use.
</blockquote></details>

I'm not sure exactly what you mean. But part of the intention is to avoid sending the full announcement except when necessary, because it can be quite large (up to 512 bytes). Also, it's important that even a node who could store the data will send back any closer nodes it knows, so that announcer and searcher end up looking at the same set of nodes.
___
*[DHTAnnouncements.md, line 94 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyfWfJDZruxbjDIvoC:-LS5qH_x7NyZCrP-jVun:b-j29pcq) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L94)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

iff meaning and only if? can we expand it?
</blockquote></details>

Yes, and yes.
___
*[DHTAnnouncements.md, line 116 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyhCay1Jpn0ftr_zsL:-LS5qLAp5hZ3jR59kD_C:b-gc906l) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L116)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

or, there was some discussion about storing messages for offline delivery in the DHT. In one of those discussions, an idea that came up was proof of work. If we add a proof of work system. If we detect possible abuse, we could simply respond to abusive nodes with a POW request every [interval] dropping packets from said node that don't include that POW
</blockquote></details>

I'm not sure what attack you're worrying about here.

The UDP amplification attack just involves forging the sender of the UDP packet to be the victim, so the victim gets any response. The amplification factor of ~3 means that using a tox node in this way would give a three-fold saving over directly sending the packets to the victim. It's bad form to have a large amplification ratio, but iiuc 3 isn't really large as these things go.
___
*[DHTAnnouncements.md, line 158 at r1](https://reviewable.io/reviews/zugz/tox-dhtannouncements/2#-LRyiXlVAURKFItIzSo4:-LS5rOKEAH-vdHjJtLb_:b-2r9ztu) ([raw file](https://github.com/zugz/tox-dhtannouncements/blob/0168cf85b22580d313d26032b5145da7ed3f9a90/DHTAnnouncements.md#L158)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

what's the difference in packet sizes?
</blockquote></details>

full announcement is up to 512 bytes (and for the intended application is ~300-400 iirc), while a reannouncement is 32 bytes.

**Comment by GrayHatter** [comment]
Why is the announcement so large?

**Comment by zugz** [comment]
Merged (after a rebase so github didn't notice).

**Comment by zugz** [comment]
* Saturday, 2018-11-24 at 10:02 -0800 - Gregory Mullen <notifications@github.com>:

>Why is the announcement so large?

Actually it's at most 300 bytes. It's a timestamp followed by our dht 
public key and then up to 4 nodes in packed format. But anyway, I wanted 
to leave room for the possibility of it growing a bit in the future, so 
512 bytes seemed like a reasonable maximum.

**Comment by GrayHatter** [comment]
The idea I had was the dht keys should rotate as well... 

But why not just send our ipport exclusively?

Yeah, because of NATs and misconfigured firewalls but, even then I assume that's such a rare case that then the friend can do it's own dht lookups if it needs to find TCP relays.

**Comment by zugz** [comment]
* Saturday, 2018-11-24 at 13:32 -0800 - Gregory Mullen <notifications@github.com>:

>The idea I had was the dht keys should rotate as well...

You mean change it every hour or something? The thing is, that only 
really helps if our IP address changes as well.

>But why not just send our ipport exclusively?
>
>Yeah, because of NATs and misconfigured firewalls but, even then 
>I assume that's such a rare case that then the friend can do it's own 
>dht lookups if it needs to find TCP relays.

Actually it seems that even most dht nodes don't accept incoming 
connections from arbitrary hosts, and of course tcp-only users can't be 
contacted on the DHT at all. So we at least need to send our dht key and 
some tcp servers we're connected to.

**Pull request closed without merging**
